// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC643loK7gptoR6bsQceMv5RIOQJ8tmFzE',
    appId: '1:522070672240:web:032a4b04afba8720fa85b5',
    messagingSenderId: '522070672240',
    projectId: 'quiz-4c367',
    authDomain: 'quiz-4c367.firebaseapp.com',
    storageBucket: 'quiz-4c367.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1c12zr-QveR0rZjDYX3TiVICBkPgj6uo',
    appId: '1:522070672240:android:1de8afb1a15f14b1fa85b5',
    messagingSenderId: '522070672240',
    projectId: 'quiz-4c367',
    storageBucket: 'quiz-4c367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB191Qa_RJsAJtkPcwMX2AN3AjzPqu56jg',
    appId: '1:522070672240:ios:73b01d1a1056b3a7fa85b5',
    messagingSenderId: '522070672240',
    projectId: 'quiz-4c367',
    storageBucket: 'quiz-4c367.appspot.com',
    androidClientId: '522070672240-jf9ce7c7p86h5b1h45m6h97ei181tvlr.apps.googleusercontent.com',
    iosClientId: '522070672240-ikb39asqbr50nddph9bted8vjc7m6sbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC643loK7gptoR6bsQceMv5RIOQJ8tmFzE',
    appId: '1:522070672240:web:9dbbb1be52152c3afa85b5',
    messagingSenderId: '522070672240',
    projectId: 'quiz-4c367',
    authDomain: 'quiz-4c367.firebaseapp.com',
    storageBucket: 'quiz-4c367.appspot.com',
  );
}
